# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000         # internal cluster port
      targetPort: 5000   # pod/container port
      nodePort: 30080    # external access port (accessible via minikube IP)
